version: '3.8'

services:
  # Backend API
  api:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - JWT_SECRET=your-super-secret-jwt-key-dev
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/silver_lining
      - REDIS_URL=redis://redis:6379
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - silver-lining-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=silver_lining
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - silver-lining-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - silver-lining-network

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@silverlining.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - silver-lining-network

volumes:
  postgres_data:
  redis_data:

networks:
  silver-lining-network:
    driver: bridge 